In [1]:
from absenteeism_module import *

In [2]:
new_data = pd.read_csv('Absenteeism_new_data.csv')
new_data.head(20)

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0

In [3]:
model = absenteeism_model('model','scaler')

In [4]:
model.load_and_clean_data('Absenteeism_new_data.csv')

In [5]:
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.127203,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.864029,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.265096,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.202894,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.719413,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.707978,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.570469,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.127203,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.133909,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.523575,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.437458,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.639695,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.344741,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.127203,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.077404,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.162866,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.639695,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.508818,1
18,0,0.0,0,1,6,291,40,25,0,1,1,0.380199,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.520152,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.139260,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.053484,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.534880,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.534880,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.053484,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.514699,1
26,0,0.0,1,0,7,233,31,21,1,1,8,0.355062,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.640744,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.139260,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.640744,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.247281,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.139260,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.483342,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.263038,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.965609,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.911216,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.757500,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.019140,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.255343,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.065876,0

In [7]:
model.predicted_outputs().to_csv('Absenteeism_predictions.csv', index = False)